#Default base image
FROM nginx
#Copy the configuration file

COPY ./default.conf /etc/nginx/conf.d/default.conf

# Again no need to add start up command because nginx is already running by default upon startup 